require:
  - rubocop-rails
  - rubocop-rspec
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
Metrics/AbcSize:
  Exclude:
    - "db/migrate/**/*"
Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*"
Metrics/BlockLength:
  Exclude:
    - "db/migrate/**/*"
  IgnoredMethods:
    - describe
Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['(\A|\s)#'] # ignored comment line
  Exclude:
    - "db/seeds/**/*"
RSpec/MultipleExpectations:
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Enabled: false
AllCops:
  NewCops: enable